* Growth

- Does the company have growth potential for the next several years
  - Prioritize quality of growth over several years as opposed to year-year comparisons
- Is management determined to continue development of products and processes to increase total sales when the growth potential has been exhausted?
  - Managers can recognize when existing opportunities have reached their potential and new developments need to be explored
  - Companies are better placed to succeed in new industries that are related to existing businesses than in new unrelated industries
- Does the company take a long-term view on profits?
- Will future company growth require new equity financing such that benefits to shareholders are offset by the dilution (from the growth) in their claim?
  - The company relies on current profits rather than contributions from shareholders
    - If a company relies on contributions from shareholders then the attractiveness of the investment depends on the dilution of the company
    - The expected growth in earnings needs to be large enough to justify the cost of dilution (p/e)

* Profit Margins

- Does the company have an attractive profit margin
  - The exception is companies willing to sacrifice current profits to accelerate their growth over the next few years
    - It is thus critical that funds go to further research - different from companies that need to reinvest their profits in projects just to stay afloat
- What is the company undertaking to protect or grow profit margins?
  - Avoid industries whose profit margins increase just as a results of price increases
- Are there characteristics unique to the business and/or industry that provide useful clues on the position of the company relative to its competitors?

* Research, sales, and accounting

- Is the company's research and development efforts effective relative to its size?
  - Leaders must coordinate people of diverse skills and backgrounds: link production, research, sales, and management
- Do they have an above average sales team?
  - Company success is based on the efficiency of the research production and sales teams
- Does the company have good cost analysis and accounting controls?

* Managerial relations and depth

- Does the company have outstanding labor and personnel relations?
  - Effective working conditions and leadership make for improved productivity
  - Compare the turnover rate and size of waiting list for job applications against competitors
  - Companies with above-average profits and above-average wages
  - Management should seek to resolve grievances and disputes quickly and fairly
  - Red flags :: mass hirings and firings based on outlook
- Depth in management
  - succession plan for key leaders
  - Managers should welcome suggestions from across the organization as well as criticism

* Honesty and integrity

- Is management candid with shareholders during good and bad news?
- Does the company have management of unquestionable integrity?

* Diversification

  - <= 20% (any one stock) in large entrenched stalwarts
  - <= 10% in fast-growers but larger stocks
  - Smaller fast-growers, never more than 5%
